IKNSA\PostBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: IKNSA\PostBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        resume:
            type: string
            length: 255
            nullable: true
        content:
            type: text
        creation:
            type: datetime
        auteur:
            type: string
            length: 255
        image:
            type: string
            length: 255
    lifecycleCallbacks: {  }
